<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- This is for the modified ZbotArctic with a car-style outer case -->
  <!-- The position of lidar changed from front to back -->
  <xacro:property name="lidar_length" value="0.0195" />
  <xacro:property name="lidar_radius" value="0.035" />
  <xacro:property name="lidar_post_radius" value="0.01" />
  <xacro:property name="lidar_post_length" value="${0.0315+0.005}" />

  <joint name="laser_joint" type="fixed">
    <parent link="chassis" />
    <child link="laser_frame" />
    <!-- <origin xyz="0.122 0 0.212" rpy="0 0 0"/> -->
    <!-- <origin xyz="${0.144-lidar_radius} 0 ${0.066+lidar_length/2}" rpy="0 0 0"/> -->
    <!-- <origin xyz="${0.144-lidar_radius-0.01} 0 ${0.066+lidar_post_length+lidar_length/2}" rpy="0 0 0" /> -->
    <origin xyz="${lidar_radius+0.01} 0 ${0.066+lidar_post_length+lidar_length/2}" rpy="0 0 0" />
  </joint>

  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}" />
      </geometry>
      <material name="black" />
    </visual>
    <visual>
      <!-- <origin xyz="0 0 -0.05"/> -->
      <origin xyz="0 0 ${-lidar_post_length/2-lidar_length/2}" />
      <geometry>
        <!-- <cylinder radius="0.01" length="0.1"/> -->
        <cylinder radius="${lidar_post_radius}" length="${lidar_post_length}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <!-- <cylinder radius="0.05" length="0.04"/> -->
        <cylinder radius="${lidar_post_radius}" length="${lidar_post_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="laser_frame">
    <material>Gazebo/Black</material>

    <sensor name="laser" type="ray">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
